apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ingress-nginx
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: crmreg.azurecr.io/crm-backend # Replace with your actual backend image
          ports:
            - containerPort: 5000
      imagePullSecrets: 
      - name: acr-secret
      

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ingress-nginx
  labels:
    app: backend
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: ingress-nginx
  # annotations: 
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    
spec:
  ingressClassName: nginx # Ensure this matches the ingress class in your cluster
  rules:
    - host: crmbe.careerdeveloper.xyz # Replace with your domain or IP for testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
  tls:
  - hosts:
    - crmbe.careerdeveloper.xyz
    secretName: crmbe-tls  
